import {MigrationInterface, QueryRunner} from "typeorm";

export class user1593757388310 implements MigrationInterface {

   public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`DROP INDEX "IDX_9a5a6a556f75c4ac7bfdd03410"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_d8791f444a8bf23fe4c1bc020c"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_6fb55742e13e8082954d0436dc"`, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_order_item" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "unitPrice" integer NOT NULL, "unitPriceIncludesTax" boolean NOT NULL, "taxRate" decimal(5,2) NOT NULL, "pendingAdjustments" text NOT NULL, "cancelled" boolean NOT NULL DEFAULT (0), "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "fulfillmentId" integer, "refundId" integer, "lineId" integer, CONSTRAINT "FK_3e5161133689fba526377cbccd3" FOREIGN KEY ("refundId") REFERENCES "refund" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_eed51be48640c21e1c76d3e9fbe" FOREIGN KEY ("fulfillmentId") REFERENCES "fulfillment" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_69384323444206753f0cdeb64e0" FOREIGN KEY ("lineId") REFERENCES "order_line" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_order_item"("createdAt", "updatedAt", "unitPrice", "unitPriceIncludesTax", "taxRate", "pendingAdjustments", "cancelled", "id", "fulfillmentId", "refundId", "lineId") SELECT "createdAt", "updatedAt", "unitPrice", "unitPriceIncludesTax", "taxRate", "pendingAdjustments", "cancelled", "id", "fulfillmentId", "refundId", "lineId" FROM "order_item"`, undefined);
        await queryRunner.query(`DROP TABLE "order_item"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_order_item" RENAME TO "order_item"`, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_tax_rate" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "enabled" boolean NOT NULL, "value" decimal(5,2) NOT NULL, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "categoryId" integer, "zoneId" integer, "customerGroupId" integer, CONSTRAINT "FK_8b5ab52fc8887c1a769b9276caf" FOREIGN KEY ("customerGroupId") REFERENCES "customer_group" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_9872fc7de2f4e532fd3230d1915" FOREIGN KEY ("zoneId") REFERENCES "zone" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_7ee3306d7638aa85ca90d672198" FOREIGN KEY ("categoryId") REFERENCES "tax_category" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_tax_rate"("createdAt", "updatedAt", "name", "enabled", "value", "id", "categoryId", "zoneId", "customerGroupId") SELECT "createdAt", "updatedAt", "name", "enabled", "value", "id", "categoryId", "zoneId", "customerGroupId" FROM "tax_rate"`, undefined);
        await queryRunner.query(`DROP TABLE "tax_rate"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_tax_rate" RENAME TO "tax_rate"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_42187bb72520a713d625389489"`, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_product_translation" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "languageCode" varchar NOT NULL, "name" varchar NOT NULL, "slug" varchar NOT NULL, "description" text NOT NULL, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "baseId" integer, "customFieldsShortname" varchar, CONSTRAINT "FK_7dbc75cb4e8b002620c4dbfdac5" FOREIGN KEY ("baseId") REFERENCES "product" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_product_translation"("createdAt", "updatedAt", "languageCode", "name", "slug", "description", "id", "baseId") SELECT "createdAt", "updatedAt", "languageCode", "name", "slug", "description", "id", "baseId" FROM "product_translation"`, undefined);
        await queryRunner.query(`DROP TABLE "product_translation"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_product_translation" RENAME TO "product_translation"`, undefined);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_42187bb72520a713d625389489" ON "product_translation" ("languageCode", "slug") `, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_product" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "enabled" boolean NOT NULL DEFAULT (1), "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "featuredAssetId" integer, "customFieldsInfourl" varchar(255), "customFieldsDownloadable" boolean DEFAULT (0), CONSTRAINT "FK_91a19e6613534949a4ce6e76ff8" FOREIGN KEY ("featuredAssetId") REFERENCES "asset" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_product"("createdAt", "updatedAt", "deletedAt", "enabled", "id", "featuredAssetId") SELECT "createdAt", "updatedAt", "deletedAt", "enabled", "id", "featuredAssetId" FROM "product"`, undefined);
        await queryRunner.query(`DROP TABLE "product"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_product" RENAME TO "product"`, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_user" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "identifier" varchar NOT NULL, "passwordHash" varchar NOT NULL, "verified" boolean NOT NULL DEFAULT (0), "verificationToken" varchar, "passwordResetToken" varchar, "identifierChangeToken" varchar, "pendingIdentifier" varchar, "lastLogin" varchar, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "customFieldsSociallogintoken" varchar(255))`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_user"("createdAt", "updatedAt", "deletedAt", "identifier", "passwordHash", "verified", "verificationToken", "passwordResetToken", "identifierChangeToken", "pendingIdentifier", "lastLogin", "id") SELECT "createdAt", "updatedAt", "deletedAt", "identifier", "passwordHash", "verified", "verificationToken", "passwordResetToken", "identifierChangeToken", "pendingIdentifier", "lastLogin", "id" FROM "user"`, undefined);
        await queryRunner.query(`DROP TABLE "user"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_user" RENAME TO "user"`, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_order_item" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "unitPrice" integer NOT NULL, "unitPriceIncludesTax" boolean NOT NULL, "taxRate" decimal(5,2) NOT NULL, "pendingAdjustments" text NOT NULL, "cancelled" boolean NOT NULL DEFAULT (0), "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "fulfillmentId" integer, "refundId" integer, "lineId" integer, CONSTRAINT "FK_3e5161133689fba526377cbccd3" FOREIGN KEY ("refundId") REFERENCES "refund" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_eed51be48640c21e1c76d3e9fbe" FOREIGN KEY ("fulfillmentId") REFERENCES "fulfillment" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_69384323444206753f0cdeb64e0" FOREIGN KEY ("lineId") REFERENCES "order_line" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_order_item"("createdAt", "updatedAt", "unitPrice", "unitPriceIncludesTax", "taxRate", "pendingAdjustments", "cancelled", "id", "fulfillmentId", "refundId", "lineId") SELECT "createdAt", "updatedAt", "unitPrice", "unitPriceIncludesTax", "taxRate", "pendingAdjustments", "cancelled", "id", "fulfillmentId", "refundId", "lineId" FROM "order_item"`, undefined);
        await queryRunner.query(`DROP TABLE "order_item"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_order_item" RENAME TO "order_item"`, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_tax_rate" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "enabled" boolean NOT NULL, "value" decimal(5,2) NOT NULL, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "categoryId" integer, "zoneId" integer, "customerGroupId" integer, CONSTRAINT "FK_8b5ab52fc8887c1a769b9276caf" FOREIGN KEY ("customerGroupId") REFERENCES "customer_group" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_9872fc7de2f4e532fd3230d1915" FOREIGN KEY ("zoneId") REFERENCES "zone" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_7ee3306d7638aa85ca90d672198" FOREIGN KEY ("categoryId") REFERENCES "tax_category" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_tax_rate"("createdAt", "updatedAt", "name", "enabled", "value", "id", "categoryId", "zoneId", "customerGroupId") SELECT "createdAt", "updatedAt", "name", "enabled", "value", "id", "categoryId", "zoneId", "customerGroupId" FROM "tax_rate"`, undefined);
        await queryRunner.query(`DROP TABLE "tax_rate"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_tax_rate" RENAME TO "tax_rate"`, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_job_record" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "queueName" varchar NOT NULL, "data" text, "state" varchar NOT NULL, "progress" integer NOT NULL, "result" text, "error" varchar, "startedAt" datetime(6), "settledAt" datetime(6), "isSettled" boolean NOT NULL, "retries" integer NOT NULL, "attempts" integer NOT NULL, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_job_record"("createdAt", "updatedAt", "queueName", "data", "state", "progress", "result", "error", "startedAt", "settledAt", "isSettled", "retries", "attempts", "id") SELECT "createdAt", "updatedAt", "queueName", "data", "state", "progress", "result", "error", "startedAt", "settledAt", "isSettled", "retries", "attempts", "id" FROM "job_record"`, undefined);
        await queryRunner.query(`DROP TABLE "job_record"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_job_record" RENAME TO "job_record"`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_6fb55742e13e8082954d0436dc" ON "search_index_item" ("productName") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_d8791f444a8bf23fe4c1bc020c" ON "search_index_item" ("productVariantName") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_9a5a6a556f75c4ac7bfdd03410" ON "search_index_item" ("description") `, undefined);
   }

   public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`DROP INDEX "IDX_9a5a6a556f75c4ac7bfdd03410"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_d8791f444a8bf23fe4c1bc020c"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_6fb55742e13e8082954d0436dc"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_record" RENAME TO "temporary_job_record"`, undefined);
        await queryRunner.query(`CREATE TABLE "job_record" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "queueName" varchar NOT NULL, "data" text, "state" varchar NOT NULL, "progress" integer NOT NULL, "result" text, "error" varchar, "startedAt" datetime(6), "settledAt" datetime(6), "isSettled" boolean NOT NULL, "retries" integer NOT NULL, "attempts" integer NOT NULL, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL)`, undefined);
        await queryRunner.query(`INSERT INTO "job_record"("createdAt", "updatedAt", "queueName", "data", "state", "progress", "result", "error", "startedAt", "settledAt", "isSettled", "retries", "attempts", "id") SELECT "createdAt", "updatedAt", "queueName", "data", "state", "progress", "result", "error", "startedAt", "settledAt", "isSettled", "retries", "attempts", "id" FROM "temporary_job_record"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_job_record"`, undefined);
        await queryRunner.query(`ALTER TABLE "tax_rate" RENAME TO "temporary_tax_rate"`, undefined);
        await queryRunner.query(`CREATE TABLE "tax_rate" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "enabled" boolean NOT NULL, "value" decimal(5,2) NOT NULL, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "categoryId" integer, "zoneId" integer, "customerGroupId" integer, CONSTRAINT "FK_8b5ab52fc8887c1a769b9276caf" FOREIGN KEY ("customerGroupId") REFERENCES "customer_group" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_9872fc7de2f4e532fd3230d1915" FOREIGN KEY ("zoneId") REFERENCES "zone" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_7ee3306d7638aa85ca90d672198" FOREIGN KEY ("categoryId") REFERENCES "tax_category" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "tax_rate"("createdAt", "updatedAt", "name", "enabled", "value", "id", "categoryId", "zoneId", "customerGroupId") SELECT "createdAt", "updatedAt", "name", "enabled", "value", "id", "categoryId", "zoneId", "customerGroupId" FROM "temporary_tax_rate"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_tax_rate"`, undefined);
        await queryRunner.query(`ALTER TABLE "order_item" RENAME TO "temporary_order_item"`, undefined);
        await queryRunner.query(`CREATE TABLE "order_item" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "unitPrice" integer NOT NULL, "unitPriceIncludesTax" boolean NOT NULL, "taxRate" decimal(5,2) NOT NULL, "pendingAdjustments" text NOT NULL, "cancelled" boolean NOT NULL DEFAULT (0), "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "fulfillmentId" integer, "refundId" integer, "lineId" integer, CONSTRAINT "FK_3e5161133689fba526377cbccd3" FOREIGN KEY ("refundId") REFERENCES "refund" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_eed51be48640c21e1c76d3e9fbe" FOREIGN KEY ("fulfillmentId") REFERENCES "fulfillment" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_69384323444206753f0cdeb64e0" FOREIGN KEY ("lineId") REFERENCES "order_line" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "order_item"("createdAt", "updatedAt", "unitPrice", "unitPriceIncludesTax", "taxRate", "pendingAdjustments", "cancelled", "id", "fulfillmentId", "refundId", "lineId") SELECT "createdAt", "updatedAt", "unitPrice", "unitPriceIncludesTax", "taxRate", "pendingAdjustments", "cancelled", "id", "fulfillmentId", "refundId", "lineId" FROM "temporary_order_item"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_order_item"`, undefined);
        await queryRunner.query(`ALTER TABLE "user" RENAME TO "temporary_user"`, undefined);
        await queryRunner.query(`CREATE TABLE "user" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "identifier" varchar NOT NULL, "passwordHash" varchar NOT NULL, "verified" boolean NOT NULL DEFAULT (0), "verificationToken" varchar, "passwordResetToken" varchar, "identifierChangeToken" varchar, "pendingIdentifier" varchar, "lastLogin" varchar, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL)`, undefined);
        await queryRunner.query(`INSERT INTO "user"("createdAt", "updatedAt", "deletedAt", "identifier", "passwordHash", "verified", "verificationToken", "passwordResetToken", "identifierChangeToken", "pendingIdentifier", "lastLogin", "id") SELECT "createdAt", "updatedAt", "deletedAt", "identifier", "passwordHash", "verified", "verificationToken", "passwordResetToken", "identifierChangeToken", "pendingIdentifier", "lastLogin", "id" FROM "temporary_user"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_user"`, undefined);
        await queryRunner.query(`ALTER TABLE "product" RENAME TO "temporary_product"`, undefined);
        await queryRunner.query(`CREATE TABLE "product" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "enabled" boolean NOT NULL DEFAULT (1), "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "featuredAssetId" integer, CONSTRAINT "FK_91a19e6613534949a4ce6e76ff8" FOREIGN KEY ("featuredAssetId") REFERENCES "asset" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "product"("createdAt", "updatedAt", "deletedAt", "enabled", "id", "featuredAssetId") SELECT "createdAt", "updatedAt", "deletedAt", "enabled", "id", "featuredAssetId" FROM "temporary_product"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_product"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_42187bb72520a713d625389489"`, undefined);
        await queryRunner.query(`ALTER TABLE "product_translation" RENAME TO "temporary_product_translation"`, undefined);
        await queryRunner.query(`CREATE TABLE "product_translation" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "languageCode" varchar NOT NULL, "name" varchar NOT NULL, "slug" varchar NOT NULL, "description" text NOT NULL, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "baseId" integer, CONSTRAINT "FK_7dbc75cb4e8b002620c4dbfdac5" FOREIGN KEY ("baseId") REFERENCES "product" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "product_translation"("createdAt", "updatedAt", "languageCode", "name", "slug", "description", "id", "baseId") SELECT "createdAt", "updatedAt", "languageCode", "name", "slug", "description", "id", "baseId" FROM "temporary_product_translation"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_product_translation"`, undefined);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_42187bb72520a713d625389489" ON "product_translation" ("languageCode", "slug") `, undefined);
        await queryRunner.query(`ALTER TABLE "tax_rate" RENAME TO "temporary_tax_rate"`, undefined);
        await queryRunner.query(`CREATE TABLE "tax_rate" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "enabled" boolean NOT NULL, "value" decimal(5,2) NOT NULL, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "categoryId" integer, "zoneId" integer, "customerGroupId" integer, CONSTRAINT "FK_8b5ab52fc8887c1a769b9276caf" FOREIGN KEY ("customerGroupId") REFERENCES "customer_group" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_9872fc7de2f4e532fd3230d1915" FOREIGN KEY ("zoneId") REFERENCES "zone" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_7ee3306d7638aa85ca90d672198" FOREIGN KEY ("categoryId") REFERENCES "tax_category" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "tax_rate"("createdAt", "updatedAt", "name", "enabled", "value", "id", "categoryId", "zoneId", "customerGroupId") SELECT "createdAt", "updatedAt", "name", "enabled", "value", "id", "categoryId", "zoneId", "customerGroupId" FROM "temporary_tax_rate"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_tax_rate"`, undefined);
        await queryRunner.query(`ALTER TABLE "order_item" RENAME TO "temporary_order_item"`, undefined);
        await queryRunner.query(`CREATE TABLE "order_item" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "unitPrice" integer NOT NULL, "unitPriceIncludesTax" boolean NOT NULL, "taxRate" decimal(5,2) NOT NULL, "pendingAdjustments" text NOT NULL, "cancelled" boolean NOT NULL DEFAULT (0), "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "fulfillmentId" integer, "refundId" integer, "lineId" integer, CONSTRAINT "FK_3e5161133689fba526377cbccd3" FOREIGN KEY ("refundId") REFERENCES "refund" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_eed51be48640c21e1c76d3e9fbe" FOREIGN KEY ("fulfillmentId") REFERENCES "fulfillment" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_69384323444206753f0cdeb64e0" FOREIGN KEY ("lineId") REFERENCES "order_line" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "order_item"("createdAt", "updatedAt", "unitPrice", "unitPriceIncludesTax", "taxRate", "pendingAdjustments", "cancelled", "id", "fulfillmentId", "refundId", "lineId") SELECT "createdAt", "updatedAt", "unitPrice", "unitPriceIncludesTax", "taxRate", "pendingAdjustments", "cancelled", "id", "fulfillmentId", "refundId", "lineId" FROM "temporary_order_item"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_order_item"`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_6fb55742e13e8082954d0436dc" ON "search_index_item" ("productName") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_d8791f444a8bf23fe4c1bc020c" ON "search_index_item" ("productVariantName") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_9a5a6a556f75c4ac7bfdd03410" ON "search_index_item" ("description") `, undefined);
   }

}
